#
# (C) Copyright 2017
#  Jack Lee 03.15, 2019
#


obj-$(CONFIG_M500774)	+= rtk_api.o
obj-$(CONFIG_M500774)	+= rtk_i2c.o
obj-$(CONFIG_M500774)	+= rtk_error.o

obj-$(CONFIG_M500774)	+= rtl8307h_reg_list.o
obj-$(CONFIG_M500774)	+= rtl8307h_asicdrv_port.o
obj-$(CONFIG_M500774)	+= rtl8307h_asicdrv_phy.o
obj-$(CONFIG_M500774)	+= rtl8307h_regField_list.o

